### ISSUE TITLE
Can congress.bills and congress.search_bills return total count?

### ISSUE THREAD

**Issue by AeroHil** [sunlightlabs/python-sunlight#26]
In the Sunlight API, there is a count at the top level of every response like this:

"count": 163,
"page": {
  "per_page": 50,
  "page": 3,
  "count": 50
}

Is this being returned from the python-sunlight project? I am only getting an array object of the results. So, if I set per_page parameter to a static number, I can't get the total count of the search, instead I always get the per_page number returned using len() or less.  It would be very useful if I can get the total count information like the REST API.

**Comment by AeroHil** [comment]
I found my own answer piecing together the source code.

For those interested getting the total count, you can use the following:
<code>total_bills = sunlight_results._meta['count'] </code>, 
where <code>sunlight_results</code> is what is returned from calling <code>sunlight.congress.search_bills</code> or <code>sunlight.congress.bills</code>

There's an object _meta that has all of the top level data

**Comment by paultag** [comment]
Yep! `_meta` should have all that stuff! :)
